# Generated by Django 2.1.7 on 2019-05-26 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Flintwood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlintCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('Product_name', models.CharField(default='', max_length=254)),
                ('Product_description', models.TextField(default='', max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('last_modified', models.DateField(default=django.utils.timezone.now)),
                ('ProductID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Flintwood.Product', verbose_name='Product')),
                ('User_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'FlintCarts',
            },
        ),
    ]
