# Generated by Django 2.1.7 on 2019-06-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flintwood', '0002_auto_20190621_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Catergory',
        ),
    ]
