# Generated by Django 2.1.7 on 2019-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flintwood', '0003_remove_product_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Unit',
            field=models.CharField(default='1kg', max_length=254),
        ),
    ]
