# Generated by Django 2.1.7 on 2019-06-21 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_address', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('buyer', 'BUYER'), ('Flintwood_supplier', 'FLINTWOOD_SUPPLIER'), ('btsupplier', 'BTTIAN_SUPPLIER'), ('biotec_supplier', 'BIOTEC_SUPPLIER')], default='buyer', max_length=10)),
                ('privilege', models.CharField(choices=[('flintwood', 'FLINTWOOD'), ('biotech', 'BIOTECH'), ('tktitan', 'TKTITAN'), ('all', 'ALL'), ('none', 'NONE')], default='none', max_length=10)),
                ('Country', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=15)),
                ('Alternate_phonenumber', models.CharField(default='none', max_length=15)),
                ('WeChat', models.CharField(default='none', max_length=15)),
                ('Skype', models.CharField(default='none', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=220, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('ended', models.BooleanField(default=False)),
                ('Activeclient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_address', models.CharField(max_length=200)),
                ('privilege', models.CharField(choices=[('superuser', 'SUPERUSER'), ('admin', 'ADMIN'), ('content', 'CONTENT_MANAGER')], default='Admin', max_length=10)),
                ('Country', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='Activeuser',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
