# Generated by Django 2.1.7 on 2019-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190526_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='privilege',
            field=models.CharField(choices=[('flintwood', 'FLINTWOOD'), ('biotech', 'BIOTECH'), ('tktitan', 'TKTITAN'), ('all', 'ALL'), ('none', 'NONE')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='privilege',
            field=models.CharField(choices=[('superuser', 'SUPERUSER'), ('admin', 'ADMIN'), ('content', 'CONTENT_MANAGER')], default='Admin', max_length=10),
        ),
    ]
