# Generated by Django 2.1.7 on 2019-05-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190526_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Alternate_phonenumber',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
