# Generated by Django 2.1.7 on 2019-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_client_alternate_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='physical_address',
            field=models.CharField(max_length=200),
        ),
    ]
