# Generated by Django 2.1.7 on 2019-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190621_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='privilege',
            field=models.CharField(choices=[('flintwood', 'FLINTWOOD'), ('biotech', 'BIOTECH'), ('tktitan', 'BTTITAN'), ('all', 'ALL'), ('none', 'NONE')], default='none', max_length=30),
        ),
    ]
