# Generated by Django 2.1.7 on 2019-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20190627_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='privilege',
            field=models.CharField(choices=[('flintwood', 'FLINTWOOD'), ('biotech', 'BIOTECH'), ('bttitan', 'BTTITAN'), ('all', 'ALL'), ('none', 'NONE')], default='none', max_length=30),
        ),
    ]
