# Generated by Django 2.1.7 on 2019-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20190526_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='physical_address',
            field=models.CharField(max_length=200),
        ),
    ]
