# Generated by Django 2.1.7 on 2019-06-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190526_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Skype',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='WeChat',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
