# Generated by Django 2.1.7 on 2019-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='freightRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(default='', max_length=254)),
                ('Destination', models.CharField(default='', max_length=254)),
                ('freightroute', models.CharField(default='', max_length=254)),
                ('metric', models.CharField(default='', max_length=254)),
                ('QuantitySent', models.IntegerField()),
                ('QuantityRecieved', models.IntegerField()),
                ('Total_cost', models.IntegerField()),
                ('Unit_cost', models.IntegerField()),
                ('Sourcetax', models.IntegerField()),
                ('Destinationtax', models.IntegerField()),
                ('MarkupRate', models.IntegerField()),
                ('Product_type', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
