# Generated by Django 2.1.7 on 2019-06-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightrate',
            name='freightroute',
            field=models.CharField(choices=[('air', 'AIR'), ('sea', 'SEA'), ('road', 'ROAD')], default='', max_length=254),
        ),
    ]
