# Generated by Django 2.1.7 on 2019-06-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0002_auto_20190624_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freightrate',
            old_name='freightroute',
            new_name='freight',
        ),
    ]
