# Generated by Django 2.1.7 on 2019-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0003_auto_20190624_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightrate',
            name='DestinAgent',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='freightrate',
            name='OriginAgent',
            field=models.CharField(default='', max_length=254),
        ),
    ]
