# Generated by Django 2.1.7 on 2019-06-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0005_auto_20190624_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freightrate',
            old_name='freight',
            new_name='Port_freight',
        ),
    ]
