# Generated by Django 2.1.7 on 2019-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0008_auto_20190628_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightrate',
            name='Product_type',
            field=models.CharField(choices=[('Mineral', 'MINERAL'), ('fresh_fruits', 'FRESH FRUITS'), ('Medicine', 'MEDICINE')], default='', max_length=254),
        ),
    ]
