# Generated by Django 2.1.7 on 2019-06-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0009_auto_20190628_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freightrate',
            old_name='Product_type',
            new_name='Product_types',
        ),
    ]
