# Generated by Django 2.1.7 on 2019-05-21 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_slug', models.SlugField()),
                ('count', models.IntegerField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('last_modified', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'LargeCart',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(default='Kenya', max_length=200)),
                ('physical_address', models.CharField(default='Nairobi', max_length=200)),
                ('privilege', models.CharField(default='Customer', max_length=10)),
                ('Userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='UserID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='product_images')),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catergory', models.CharField(max_length=200)),
                ('Catergory_summary', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Product Catergories',
            },
        ),
        migrations.CreateModel(
            name='ProductCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=200)),
                ('Company_summary', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Product Companies',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=220, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('ended', models.BooleanField(default=False)),
                ('Activeuser', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productcatergory',
            name='Product_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecommerce.ProductCompany', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Catergory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecommerce.ProductCatergory', verbose_name='Catergory'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecommerce.ProductCompany', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Member_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecommerce.Member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ProductID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecommerce.Product', verbose_name='Product'),
        ),
    ]
