# Generated by Django 2.1.7 on 2019-05-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='product_images')),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catergory', models.CharField(max_length=200)),
                ('Catergory_summary', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Product Catergories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Catergory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='TKTitan.ProductCatergory', verbose_name='Catergory'),
        ),
    ]
