# Generated by Django 2.1.7 on 2019-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TKTitan', '0002_auto_20190621_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Unit',
            field=models.CharField(default='grams', max_length=254),
        ),
    ]
