# Generated by Django 2.1.7 on 2019-06-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TKTitan', '0003_auto_20190627_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand_Name',
            field=models.CharField(default='Mineral', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Catergory',
            field=models.CharField(default='', max_length=254),
        ),
    ]
