# Generated by Django 2.1.7 on 2019-06-21 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biotech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('Product_name', models.CharField(default='', max_length=254)),
                ('Product_description', models.TextField(default='', max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('last_modified', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Brand_Name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='Packaging',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='Unit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='biosupplierid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='biotech_supplier', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cart',
            name='ProductID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Biotech.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='User_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
