# Generated by Django 2.1.7 on 2019-05-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotechorders',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flintwoodorders',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tktitanorders',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biotechorders',
            name='Order_Payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flintwoodorders',
            name='Order_Payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tktitanorders',
            name='Order_Payment',
            field=models.BooleanField(default=False),
        ),
    ]
