# Generated by Django 2.1.7 on 2019-05-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190527_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biotechorders',
            name='OrderList',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='flintwoodorders',
            name='OrderList',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tktitanorders',
            name='OrderList',
            field=models.CharField(max_length=2000),
        ),
    ]
